#!/usr/bin/env bash

export CONTECO_LABEL="package.ingest_sasl - ModEco"
export CONTECO_DESCRIPTION="The ingest package based on filebeat with Kafka input."

export CONTECO_TYPE="package"
export CONTECO_NAME="ingest_kafka_sasl"
export CONTECO_TAG="7.9.2"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
