#!/usr/bin/env bash


prefix="package_ingest_kafka_sasl_$2"


executionplane --silent docker container prune --force

if [[ "package_ingest_kafka_sasl_ingest_kafka_sasl_filebeat_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "package_ingest_kafka_sasl_ingest_kafka_sasl_filebeat_volume"
			result=$(docker volume ls | grep "package_ingest_kafka_sasl_ingest_kafka_sasl_filebeat_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
