#!/usr/bin/env bash


prefix="package_$2"

if [[ "package_ingest_kafka_sasl_filebeat_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_ingest_kafka_sasl_filebeat_volume
	fi
	
